### ISSUE TITLE
Opening issues instead of opening pull requests would reduce the risk of merge conflicts

### ISSUE THREAD

**Issue by peterhellberg** [vienno/swe-scrapers#6]
Keeping a single Markdown file in sync between multiple pull requests is almost impossible and will probably result in a lot of merge conflicts.

It would probably be easier to just add new scrapers/client to the list by opening issues and then having a person with commit access to the repo add them to the README.

**Comment by miroli** [comment]
You're probably right. I'll update the instructions in the README.
